#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 6 contracts individually..."
echo ""

echo "Building AdminUpgradeabilityProxy (contract_AdminUpgradeabilityProxy_84db)"
FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_84db forge build || {
  echo "❌ Failed to build AdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_84db forge build"
}
echo "✅ Built AdminUpgradeabilityProxy"
echo ""

echo "Building AdminUpgradeabilityProxy (contract_AdminUpgradeabilityProxy_e95a)"
FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_e95a forge build || {
  echo "❌ Failed to build AdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_e95a forge build"
}
echo "✅ Built AdminUpgradeabilityProxy"
echo ""

echo "Building AdminUpgradeabilityProxy (contract_AdminUpgradeabilityProxy_d01e)"
FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_d01e forge build || {
  echo "❌ Failed to build AdminUpgradeabilityProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AdminUpgradeabilityProxy_d01e forge build"
}
echo "✅ Built AdminUpgradeabilityProxy"
echo ""

echo "Building GlobalPool_R46 (contract_GlobalPool_R46_ecce)"
FOUNDRY_PROFILE=contract_GlobalPool_R46_ecce forge build || {
  echo "❌ Failed to build GlobalPool_R46"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_GlobalPool_R46_ecce forge build"
}
echo "✅ Built GlobalPool_R46"
echo ""

echo "Building AETH_R21 (contract_AETH_R21_e672)"
FOUNDRY_PROFILE=contract_AETH_R21_e672 forge build || {
  echo "❌ Failed to build AETH_R21"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AETH_R21_e672 forge build"
}
echo "✅ Built AETH_R21"
echo ""

echo "Building FETH_R20 (contract_FETH_R20_518d)"
FOUNDRY_PROFILE=contract_FETH_R20_518d forge build || {
  echo "❌ Failed to build FETH_R20"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_FETH_R20_518d forge build"
}
echo "✅ Built FETH_R20"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
